[build]
  command = "echo 'No build needed'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/:name"
  to = "/.netlify/functions/:name"
  status = 200
